var paeiouIcons = ["fab",
"can",
"quincy",
"saboteur",
"arc",
"luddite",
"foxhound",
"gale",
"ogre",
"monitor",
"hermit",
"monarch",
"power_plant",
"crawler_factory",
"plug",
];
model.strategicIcons(model.strategicIcons().concat(paeiouIcons));